development:
  adapter: postgresql
  database: davidkyoo_dev
  encoding: unicode
  pool: 5
  timeout: 5000
  username: yookd

test:
  adapter: postgresql
  database: davidkyoo_test
  encoding: unicode
  pool: 5
  timeout: 5000
  username: yookd

production:
  adapter: postgresql
  database: davidkyoo
  encoding: unicode
  pool: 5
  timeout: 5000
  username: yookd
